# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# prompt
function _update_ps1() {
    local PREV_ERROR=$?
    local JOBS=$(jobs -p | wc -l)
    export PS1="$(python2.7 ~/.shline/shline.py --mode patched --prev-error $PREV_ERROR --jobs $JOBS 2> /dev/null)"
}
export PROMPT_COMMAND="_update_ps1"

# enable color support of ls and also add handy aliases
if [[ "$TERM" != "dumb" ]]; then
    if [[ `uname` == "Linux"  ]]; then
        eval "`dircolors -b`"
        alias ls='ls --color=auto'
    else
        alias ls='ls -G'
    fi
fi

# aliases
function _cd_work()
{
    for workdir in "$HOME/work/ag-projects" "$HOME/work/src"
    do
        if [[ -d "$workdir" ]]; then
            cd $workdir
            break
        fi
    done
}

function _tmux_new_or_attach()
{
    tmux has-session -t $1 2>/dev/null
    if [ "$?" -eq 1 ] ; then
        # No session found
        tmux -2 new-session -d -s $1
    fi
    tmux -2 attach-session -t $1
}

alias tmux='tmux -2'
alias t=_tmux_new_or_attach

if hash "tmux" > /dev/null 2>&1; then
    alias tmux='TMPDIR=/tmp tmux -2'
fi

function _weather()
{
    curl -4 wttr.in/${1:-Amsterdam}
}

alias weather=_weather

alias ll='ls -lF -h'
alias la='ls -lFa -h'
alias l='ls -CF -h'

alias ..='cd ..'
alias cd..='cd ..'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if hash "ack-grep" > /dev/null 2>&1; then
    alias ack='ack-grep'
fi

alias du='du -sh'
alias df='df -h'

alias serve='python -m SimpleHTTPServer'

if [[ `uname` == "Darwin"  ]]; then
    alias syslog='tail -f /var/log/system.log'
    alias xopen='open'
    alias ldd='otool -L'
else
    alias syslog='tail -f /var/log/syslog'
    alias xopen='xdg-open'
fi

if [[ `uname` == "Linux"  ]]; then
    alias screen-off='xset dpms force off'
fi

# Bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [[ `uname` == "Darwin"  ]]; then
    if hash "brew" > /dev/null 2>&1; then
        if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
            . $(brew --prefix)/share/bash-completion/bash_completion
        fi
    fi
fi

# Terminal copy & paste
if [[ `uname` != "Darwin"  ]]; then
    alias pbcopy='xclip -in -selection clipboard'
    alias pbpaste='xclip -out -selection clipboard'
fi

# Home directory bin apps
export PATH=~/bin:~/.local/bin/:$PATH

# Cabal
export PATH=~/.cabal/bin:$PATH

# local paths
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# Always dump the core
ulimit -c unlimited

# ViM
alias vi='vim'
export EDITOR=vim

# Work
alias work=_cd_work
export DEBEMAIL="Saul Ibarra <saul@ag-projects.com>"

# language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
[[ -f /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh ]] && source /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh
[[ -f /usr/local/bin/virtualenvwrapper_lazy.sh ]] && source /usr/local/bin/virtualenvwrapper_lazy.sh

# Bash completion for git
[[ -s $HOME/.git-completion.bash ]] && source $HOME/.git-completion.bash

# Pythonz
[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc

# Node
NPM_PACKAGES="$HOME/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

# Darcs
export DARCS_PAGER="less -R"
export DARCS_ALWAYS_COLOR=1

# Cleanup PATH
export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

