# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# prompt
export GOPATH=${GOPATH:-~/go}
function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -error $? -colorize-hostname -newline -cwd-mode plain -modules ssh,git,hg,venv,user,host,cwd)"
}
if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# enable color support of ls and also add handy aliases
if [[ "$TERM" != "dumb" ]]; then
    if [[ `uname` == "Linux"  ]]; then
        eval "`dircolors -b`"
        alias ls='ls --color=auto'
    else
        alias ls='ls -G'
    fi
fi

# aliases
function _tmux_new_or_attach()
{
    tmux has-session -t $1 2>/dev/null
    if [ "$?" -eq 1 ] ; then
        # No session found
        tmux -2 new-session -d -s $1
    fi
    tmux -2 attach-session -t $1
}

alias tmux='tmux -2'
alias t=_tmux_new_or_attach

if hash "tmux" > /dev/null 2>&1; then
    alias tmux='TMPDIR=/tmp tmux -2'
fi

function _weather()
{
    curl -4 wttr.in/${1:-Amsterdam}
}

alias weather=_weather

alias ll='ls -lF -h'
alias la='ls -lFa -h'
alias l='ls -CF -h'

alias ..='cd ..'
alias cd..='cd ..'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if hash "ack-grep" > /dev/null 2>&1; then
    alias ack='ack-grep'
fi

alias du='du -sh'
alias df='df -h'

alias serve='python -m SimpleHTTPServer'

if [[ `uname` == "Darwin"  ]]; then
    alias syslog='tail -f /var/log/system.log'
    alias xopen='open'
    alias ldd='otool -L'
else
    alias syslog='tail -f /var/log/syslog'
    alias xopen='xdg-open'
fi

if [[ `uname` == "Linux"  ]]; then
    alias screen-off='xset dpms force off'
fi

alias timestamp='date +%Y-%m-%dT%H:%M:%S%z'

# Bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [[ `uname` == "Darwin"  ]]; then
    if hash "brew" > /dev/null 2>&1; then
        if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
            . $(brew --prefix)/share/bash-completion/bash_completion
        fi
    fi
fi

# Colored man pages
man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
}

# Terminal copy & paste
if [[ `uname` != "Darwin"  ]]; then
    alias pbcopy='xclip -in -selection clipboard'
    alias pbpaste='xclip -out -selection clipboard'
fi

# Home directory bin apps
export PATH=~/bin:~/.local/bin:$PATH

# Cabal
export PATH=~/.cabal/bin:$PATH

# local paths
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# Always dump the core
ulimit -c unlimited

# ViM
alias vi='vim'
export EDITOR=vim

# language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
[[ -f /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh ]] && source /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh
[[ -f /usr/local/bin/virtualenvwrapper_lazy.sh ]] && source /usr/local/bin/virtualenvwrapper_lazy.sh

# Bash completion for git
[[ -s $HOME/.git-completion.bash ]] && source $HOME/.git-completion.bash

# Pythonz
[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc

# Android
if [[ -d ~/Library/Android/sdk ]]
then
    export ANDROID_HOME=~/Library/Android/sdk
    export PATH=${PATH}:${ANDROID_HOME}/tools
    export PATH=${PATH}:${ANDROID_HOME}/platform-tools
fi

# Google Depot Tools
if [[ -d ~/src/depot_tools ]]
then
    export PATH=~/src/depot_tools:${PATH}
fi

# Node
NPM_PACKAGES="$HOME/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

# Darcs
export DARCS_PAGER="less -R"
export DARCS_ALWAYS_COLOR=1

# Cleanup PATH
export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

# Extra customizations
[[ -f ~/.bashrc-extra ]] && source ~/.bashrc-extra

