format = """
[](fg:#9A348E)\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$jobs\
$time\
[](fg:#6272A4)\
$line_break\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[hostname]
ssh_only = true
style = "bg:#9A348E"
format = '[$ssh_symbol$hostname ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_state]
style = "bg:#FCA17D"
format = '[\($state($progress_current/$progress_total)\)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$conflicted$deleted$renamed$modified$typechanged$staged$ahead_behind ]($style)'
ignore_submodules = true

[jobs]
symbol = "✦"
symbol_threshold = 1
number_threshold = 1
style = "bg:#F1FA8C fg:#282A36"
format = '[ $symbol $number ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#6272A4"
format = '[ $time ]($style)'
